#page title
page_title                                : Slotcar - GearClac                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6740806046                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : de                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/slotcar-gearcalc/id6740806046                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Berechne und vergleiche das Übersetzungsverhältnis deines Slotcars. Optimiere dein Setup mit GearCalc – einfach Eingeben, Berechnen und Performance testen!

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Dennis Brieske
your_link                                 : https://h-gp.de
your_city                                 :
email_address                             :
facebook_username                         :                                           
instagram_username                        : hamwardegp
twitter_username                          :
github_username                           : dennisbrieske
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Getriebe- & Geschwindigkeitsberechnung
    description                           : Berechnung der Übersetzung (Gear Ratio) anhand von Motorritzel & Kronrad. Ermittlung der zurückgelegten Strecke pro Radumdrehung und Berechnung der Geschwindigkeit in cm/s oder anderen Einheiten.
    fontawesome_icon_name                 : calculator
    
  - title                                 : Anpassbare Ergebnisausgabe
    description                           : Individuelle Anzeigeoptionen für Übersetzungsverhältnis, Strecke pro Umdrehung und Geschwindigkeit. Unterstützung für internationale Einheiten.
    fontawesome_icon_name                 : cogs

  - title                                 : Ergebnismanagement
    description                           : Mehrere Berechnungen speichern und vergleichen. Setze eine Berechnung als Referenzwert für den Vergleich. Lösche einzelne Ergebnisse nach Bedarf.
    fontawesome_icon_name                 : chart-line

  - title                                 : Benutzerfreundlichkeit
    description                           : Einfache Eingabe mit automatischer Formatierung. Kompatibel mit Dezimal- & Ganzzahlen. Eingaben und Einstellungen bleiben gespeichert.
    fontawesome_icon_name                 : toolbox

  - title                                 : Mehrsprachige Unterstützung
    description                           : Die App ist in mehreren Sprachen verfügbar, sodass Nutzer weltweit von den Funktionen profitieren können.
    fontawesome_icon_name                 : globe

  - title                                 : Modernes & intuitives Design
    description                           : Übersichtliches, anpassbares Layout für eine optimale Nutzererfahrung auf Smartphones und Tablets.
    fontawesome_icon_name                 : mobile

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
