#page title
page_title                                : Slotcar - GearClac                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6740806046                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : en                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/slotcar-gearcalc/id6740806046                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Calculate and compare the gear ratio of your slot car. Optimize your setup with GearCalc – simply input, calculate, and test performance!

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Dennis Brieske
your_link                                 : https://h-gp.de
your_city                                 :
email_address                             :
facebook_username                         :                                           
instagram_username                        : hamwardegp
twitter_username                          :
github_username                           : dennisbrieske
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Gear & Speed Calculation
    description                           : Calculation of the gear ratio based on the motor pinion and crown wheel. Determining the distance covered per wheel rotation and calculating the speed in cm/s or other units.
    fontawesome_icon_name                 : calculator
    
  - title                                 : Customizable Result Output
    description                           : Custom display options for gear ratio, distance per rotation, and speed. Supports international units.
    fontawesome_icon_name                 : cogs

  - title                                 : Result Management
    description                           : Save and compare multiple calculations. Set one calculation as the reference value for comparison. Delete individual results as needed.
    fontawesome_icon_name                 : chart-line

  - title                                 : User-Friendliness
    description                           : Easy input with automatic formatting. Compatible with decimal and whole numbers. Inputs and settings remain saved.
    fontawesome_icon_name                 : toolbox

  - title                                 : Multilingual Support
    description                           : The app is available in multiple languages, so users worldwide can benefit from its features.
    fontawesome_icon_name                 : globe

  - title                                 : Modern & Intuitive Design
    description                           : Clear, customizable layout for an optimal user experience on smartphones and tablets.
    fontawesome_icon_name                 : mobile

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
